---
  - name: PHP | Install php7.0
    apt: pkg={{ item }} state=latest force=yes
    with_items:
      - php-fpm
      - php-mysql
      - php-cli
      - php-curl
      - php-gd
      - php-mbstring
      - php7.0-dom
      - php7.0-zip

  - name: PHP | Check if Composer is installed.
    stat: "path=/usr/local/bin/composer"
    register: composer_bin

  - name: PHP | Retrieve Composer installer
    get_url:
      url: https://getcomposer.org/installer
      dest: /tmp/composer-installer.php
      mode: 0755
    when: not composer_bin.stat.exists

  - name: PHP | Run Composer installer
    command: >
      php composer-installer.php 
      chdir=/tmp
    when: not composer_bin.stat.exists

  - name: PHP | Move Composer into globally-accessible location.
    shell: >
      mv /tmp/composer.phar /usr/local/bin/composer
      creates=/usr/local/bin/composer
    when: not composer_bin.stat.exists

  - name: PHP | Ensure listen.group is set.
    lineinfile: dest=/etc/php/7.0/fpm/pool.d/www.conf regexp='listen.group = www-data' line='listen.group = www-data' state=present
    notify: php7.0-fpm-restart

  - name: PHP | Ensure listen.owner is set.
    lineinfile: dest=/etc/php/7.0/fpm/pool.d/www.conf regexp='listen.owner = www-data' line='listen.owner = www-data' state=present
    notify: php7.0-fpm-restart

  - name: PHP | Ensure listen.mode is set.
    lineinfile: dest=/etc/php/7.0/fpm/pool.d/www.conf regexp='listen.mode = 0660' line='listen.mode = 0660' state=present
    notify: php7.0-fpm-restart

  - name: PHP | Add vendor/bin to the user's path
    shell: echo 'export PATH="$PATH:/var/www/vendor/bin"' >> ~/.bashrc
